# Generated by Django 5.2.8 on 2025-12-02 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.CharField(primary_key=True, serialize=False)),
                ('sales_date', models.DateField(auto_now_add=True)),
                ('sales_price', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApp.customer')),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApp.staff')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApp.car')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(primary_key=True, serialize=False)),
                ('service_date', models.DateField(auto_now_add=True)),
                ('service_type', models.IntegerField()),
                ('service_cost', models.IntegerField()),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApp.staff')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApp.car')),
                ('staffr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApp.customer')),
            ],
        ),
    ]
