# Generated by Django 5.2.8 on 2025-12-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0002_sales_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='staffr_id',
        ),
        migrations.AddField(
            model_name='service',
            name='service_note',
            field=models.TextField(default='defaults for previous entry'),
            preserve_default=False,
        ),
    ]
