# Generated by Django 5.2.8 on 2025-12-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0003_remove_service_staffr_id_service_service_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(),
        ),
    ]
