# Generated by Django 5.2.8 on 2025-12-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0004_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='Available'),
        ),
    ]
