# Generated by Django 5.2.8 on 2025-12-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0006_alter_service_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.CharField(choices=[('sales', 'Sales'), ('services', 'Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
