# Generated by Django 5.2.8 on 2025-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0007_alter_car_car_id_alter_car_colour_alter_car_make_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='Customer_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='Staff_id',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Staff_id',
            new_name='staff_id',
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_note',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=30),
        ),
    ]
